### ISSUE TITLE
Feedback for "Account Models With Directories and Subaccounts [Feature Set B]"

### ISSUE THREAD

**Issue by ncktz-cbs** [SAP-docs/btp-best-practices-guide#12]
https://help.sap.com/docs/BTP/df50977d8bfa4c9a8a063ddb37113c43/b5a6b58694784d0c9f4ff85f9b7336dd.html

Best practices for Kyma would be a great addition.
Some ideas:
- what is the impact on the proposed Subaccount structure when using Kyma 
          - instead of or 
          - in addition to CF
- What is the proposed namespace structure (when to use a new namespace)
- naming conventions 
- etc.

**Comment by annawenger20** [comment]
Hi @ncktz-cbs,
first of all, I apologize for only reacting now. I'll check with dev/pm if we can give some recommendations for Kyma. Thanks a lot for this feedback. Kyma is not yet fully covered in this guide. 
Best regards
Anna

**Comment by grego952** [comment]
Hi all,
I received the following feedback:
> Kyma access setup is totally different from sap btp access setup.
For namespaces, you can follow what is being done in the k8s ecosystem: create ns for different teams or based on different scenarios.
The naming convention is again a matter of taste or whatever convention you have followed for your CF org/spaces.

Please let me know if more information is needed.

**Comment by ncktz-cbs** [comment]
Hi Grzegorz,

as mentioned by you, “Kyma access setup is totally different from sap btp access setup.” 
For this reason, best practices for Kyma must be covered in the BTP Best Practices Guide. From my point of view, for many customers K8s is a completely new topic. For this reason, they expect recommendations from SAP for naming conventions, namespaces and how this setup should be done in the most feasible way ensuring sustainable operations for the next years.
Starting with a suboptimal setup due to missing best practices usually leads to significantly increased effort in the upcoming years (or due a costly migration to a new stucture).

Additional questions in this context (in addition to the ones above):
- How to split projects/teams with Kyma?
- When does it make sense to create a new Kyma instance (--> new subaccount)?
- When does it make sense to create new namespaces
- etc.
- Everything while keeping in mind that a new Kyma instance does come with an additional price tag - in contrary to a new CF subaccount.

Thanks a lot
Nico

**Comment by grego952** [comment]
Hi Nico,
Thanks for your feedback.
Since it's a more complex topic, it will be covered by [REDACTED by org owner].

**Comment by ncktz-cbs** [comment]
Hi Grzegorz,

Unfortunately, I cannot access your link. Could you please provide updates here?

Thanks a lot
Nico

**Comment by grego952** [comment]
Hi Nico,
Oh, sorry, my bad. It's Kyma's internal link for the managed offering and critical issues.
Basically, the issue covers what you mentioned here and more (onboarding, security, cluster and namespace structure, etc.)
I'll keep you posted about the progress.

Best regards,
Grzegorz

**Comment by NHingerl** [comment]
Hi Nico, 
thank you for your patience and for your great input! :) 

I'm currently consolidating your feedback with our other plans to improve the guide and we'll come back to you with updates once they're available. As Anna mentioned, it's pretty complex and may take a while, but we're on it!

Best regards,
Nina

**Comment by ncktz-cbs** [comment]
Hi Nina,

Any updates on this topic?

Best regards
Nico

**Comment by NHingerl** [comment]
Hi Nico - still working on it :) 

Best regards, 
Nina

**Comment by NHingerl** [comment]
Hi Nico, thank you for your patience, we're still on it. 
It takes longer because just slapping the Kyma information (that you and others requested) onto the existing docs might not be helpful; and a more thorough review is ongoing.

I trust that you know how to get in touch with our support if you need specific answers urgently?

**Comment by ncktz-cbs** [comment]
Hi Nina,

yes, I also have direct contacts through my work at DSAG.

Thanks a lot
Nico

**Comment by NHingerl** [comment]
Perfect! 
We're still working on the docs and will let you know once there are news :)

**Comment by je-hal** [comment]
This issue was last updated 75 days ago. Is there any update?

**Comment by NHingerl** [comment]
We're still working on it but it may still take a while.

**Comment by NHingerl** [comment]
@ncktz-cbs major overhaul of that section is in the works, thank you for your input (and for you patience)!

**Comment by NHingerl** [comment]
@ncktz-cbs the new structure is taking shape, we're hoping we can give a more concrete update soon.

**Comment by NHingerl** [comment]
Hi @ncktz-cbs, the BPG, especially the sections for Account Model Setup and Security Setup, has been updated and published now. We expect for reiterative improvements based on future feedback.

Thanks for your patience and your great input! :) 
Nina

**Comment by ncktz-cbs** [comment]
Hi Nina,
Thanks a lot for the update! Great to have Kyma finally covered in the BTP Best Practice Guide :) 
One thing that might be beneficial to add are naming convention suggestions for Kyma - similar to https://help.sap.com/docs/btp/best-practices/account-models-with-directories-and-subaccounts-feature-set-b for Cloud Foundry

**Comment by NHingerl** [comment]
Thank you! We'll continue with further improvements, there's still more in the pipeline :) 

Those naming conventions deal with the complexities of naming when you also have directories. 
My assumption for Kyma is that the number of subaccounts typically is rather small (2-3 subaccounts), with no need for directories to keep the overview. So the applicable naming conventions would probably go into the sister page [Account Model with Subaccounts](https://help.sap.com/docs/btp/best-practices/account-models-with-subaccounts?version=Cloud). Do you concur with this assumption?

Alternatively, we could extract the naming conventions section from [Account Model With Directories and Subaccounts](https://help.sap.com/docs/btp/best-practices/account-models-with-directories-and-subaccounts-feature-set-b?version=Cloud#example-of-naming-conventions-for-this-account-model-in-the-cloud-foundry-environment) and create a separate document about "Suggested Naming Conventions", with examples for CF and Kyma; thus avoiding to spread the information across several pages.

Do you have any preference regarding these approaches? What would feel most intuitive to you?

**Comment by ncktz-cbs** [comment]
Hi Nina,
Thanks for you swift response! 
I prefer the second approach, so the naming conventions are placed a bit more prominent and easier to find. They could then be sorted by GA/SA (relevant for all), CF, Kyma and potentially ABAP (not sure if relevant). 
Generally, I think it makes sense to have a Kyma-specific section in all the places where there is a CF & Neo-specific section e.g. under 'Setting Up Access to Remote Systems' or 'Go Live and Monitor', otherwise it just brings up questions. But probably this is already on your list :)

**Comment by NHingerl** [comment]
Sounds good :) 
I'll keep you updated about further progress. 

Thanks a lot for your valuable feedback and contribution!

**Comment by NHingerl** [comment]
Hi @ncktz-cbs, we've updated the Best Practices Guide, including the recommendations about the Account Model.
Please take a look at the following documents and let us know what you think.

[Setting Up Your Account Model](https://help.sap.com/docs/btp/best-practices/setting-up-your-account-model?locale=en-US&version=Cloud)
        [Creating a Staged Development Environment](https://help.sap.com/docs/btp/best-practices/considerations-for-account-model-setup?locale=en-US&version=Cloud)
            [Staged Development with Cloud Foundry](https://help.sap.com/docs/btp/best-practices/special-considerations-for-cloud-foundry-environment?locale=en-US&version=Cloud)
            [Staged Development with Kyma](https://help.sap.com/docs/btp/best-practices/considerations-for-kyma-environment?locale=en-US&version=Cloud)
        [Checklist for the Account Model Setup](https://help.sap.com/docs/btp/best-practices/checklist-for-account-model-setup?locale=en-US&version=Cloud)
        [Naming Conventions for SAP BTP Accounts](https://help.sap.com/docs/btp/best-practices/naming-conventions-for-sap-btp-accounts?locale=en-US&version=Cloud)

**Comment by NHingerl** [comment]
Thank you all for the fantastic collaboration! 
I'd like to close this issue now, but we are going to continue improving the Best Practices Guide and other BTP docs.

Don't hesitate to open new issues or provide feedback through any other channel if there's anything you'd like us to improve.
