### ISSUE TITLE
Feedback for "Building Teams"

### ISSUE THREAD

**Issue by ncktz-cbs** [SAP-docs/btp-best-practices-guide#13]
https://help.sap.com/docs/BTP/df50977d8bfa4c9a8a063ddb37113c43/fdeddf22a6964d86a199b9eb11c7075e.html

It might make sense to rename "Cloud Administration Team" to "Platform Engineering Team". It  is a pretty widely-used name nowadays and the description of the tasks fit exactly to the definition of a "Platform Engineering Team" - enable the Cloud Development Team to do whatever they want to do.

**Comment by annawenger20** [comment]
Hi @ncktz-cbs , thanks a lot for this feedback. I like your suggestion and just changed it to Platform Engineering Team. The docs will be updated with the next release on SAP Help Portal.
