### ISSUE TITLE
Feedback for "Destination Authentication Methods"

### ISSUE THREAD

**Issue by fwilhe** [SAP-docs/btp-best-practices-guide#18]
https://help.sap.com/docs/BTP/df50977d8bfa4c9a8a063ddb37113c43/765423ddb66147bc8141607a8522fe65.html

Hi, I think this page is helpful, but it could use some attention from doc developers. The descriptions of the methods are quite sparse and this page could be rewritten in a way that is more helpful for people who don't know all the concepts mentioned there already. Probably a table is not the best structure element for this kind of documentation.

I'd prefer this page to have a section for each method where a bit more details are explained about what the method is and which fields / information need to be configured for destinations with that given method.

Best,
Florian

**Comment by annawenger20** [comment]
Thanks a lot for this feedback. @Frank1Mueller will look into it.

**Comment by Frank1Mueller** [comment]
Hi @annawenger20 ,


the mentioned methods are described in detail in the Connectivity documentation.

Maybe you (or the topic owner, respectively) could just include the related links.

I don't think it would make sense to duplicate the whole content here.

These are the links:

CF: https://help.sap.com/docs/CP_CONNECTIVITY/cca91383641e40ffbe03bdc78f00f681/42a0e6b966924f2e902090bdf435e1b2.html?version=Cloud

Neo: https://help.sap.com/docs/CP_CONNECTIVITY/b865ed651e414196b39f8922db2122c7/b068356dd7c34cf7ad6b6023deeb317d.html?version=Cloud

Best

Frank

**Comment by annawenger20** [comment]
Hi @fwilhe 
we followed Frank's advice and added the links to this chapter. It will be visible on SAP Help Portal with the next update. 
Thanks a lot for this conribution and kind regards
Anna
