### ISSUE TITLE
Typo: Establishing a Provider/Subscriber Scenario Using Multitenancy

### ISSUE THREAD

**Issue by weisensen** [SAP-docs/btp-best-practices-guide#2]
The provider/subscriber approach is one of the important scenarios **that that** are supported with multitarget application.

There are two that here, one of them should be removed.

**Comment by weisensen** [comment]
Add the link below:
[https://github.com/SAP-docs/btp-best-practices-guide/blob/main/docs/develop-and-build/Establishing_a_ProviderSubscriber_Scenario_Using_Multitenancy_617af9b.md#establishing-a-providersubscriber-scenario-using-multitenancy](url)

**Comment by annawenger20** [comment]
Thanks for spotting this! Will be fixed with the next version on SAP Help Portal. 
Kind regards, Anna
