### ISSUE TITLE
Feedback for "Security Concepts"

### ISSUE THREAD

**Issue by NHingerl** [SAP-docs/btp-best-practices-guide#20]
https://help.sap.com/docs/btp/best-practices/security-concepts?locale=en-US&version=Cloud

In section [Identity Management and Authorization Management](https://help.sap.com/docs/btp/best-practices/security-concepts?locale=en-US&version=Cloud#identity-management-and-authorization-management), I find it hard to keep an overview on the different services mentioned in prose text. My brain would prefer a list or potentially, two (for Authentication / Authorization), not quite sure.

- SAML
- OpenID Connect
- SAP ID Service (with SAP Universal ID?)
- Own identity provider
- SAP Cloud Identity Services - Identity Authentication.

**Comment by annawenger20** [comment]
Thanks, Nina! Prasi, could you have a look at this and make the change in the 4a version? 
Thanks a lot! Anna

**Comment by Prasihub** [comment]
@annawenger20 @NHingerl : Michael and I will discuss this and get back to you both :)

**Comment by Prasihub** [comment]
@NHingerl @annawenger20: We've made some changes to the section - please take a look :-)

https://help.sap.com/docs/btp/best-practices/security-concepts?state=DRAFT

**Comment by NHingerl** [comment]
Looks good to me!

**Comment by annawenger20** [comment]
Closing as this change will go live with the next release.

**Comment by NHingerl** [comment]
> Thank you for your valuable feedback contribution, @NHingerl! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://people.sap.com/nhingerl
