### ISSUE TITLE
Feedback for "Basic Platform Concepts"

### ISSUE THREAD

**Issue by ncktz-cbs** [SAP-docs/btp-best-practices-guide#21]
https://help.sap.com/docs/btp/best-practices/basic-platform-concepts

Is the diagram still correct? A global account doesn't have a region according to my understaning (at least it cannot be chosen). 

In addition, with hybrid global accounts it can also support two license types: subscription + CPEA/PAYG.

**Comment by annawenger20** [comment]
Thanks for the feedback - @AnjaNicoleKretz just recently updated this topic with exactly those two issues. I think it will be visible on SAP Help Portal with the next update (May 4th). 
@AnjaNicoleKretz can you confirm am close this issue?

**Comment by AnjaNicoleKretz** [comment]
@annawenger20  yes this has been  updated and will be visible with the next release.
