### ISSUE TITLE
Feedback for "Implementing Failover"

### ISSUE THREAD

**Issue by mar-hol** [SAP-docs/btp-best-practices-guide#3]
In context of SAP BTP, it is mostly referred to a Availability Zone or Region. Also as we refer to Multi-AZ set-up for services etc. So maybe I would be better understandable than talking of "data center". Also a section with more detailed guidance on how to set up a high-availability and a disaster recovery in BTP Multi-Cloud would be helpful.
https://help.sap.com/products/BTP/df50977d8bfa4c9a8a063ddb37113c43/df972c5529004c428e05a90966d17dca.html?version=Cloud

**Comment by annawenger20** [comment]
Hi @mar-hol, a few chapters up in the TOC, please see [Develop Resilient Applications](https://help.sap.com/products/BTP/df50977d8bfa4c9a8a063ddb37113c43/b1b929a5aea64571b2f74e810b622568.html?locale=en-US&version=Cloud). From there, you'll find links to detailed guidance for setting up resilience, high availability, and disaster recovery. Also see [Regions](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/350356d1dc314d3199dca15bd2ab9b0e.html?locale=en-US). 
Thanks a lot for your feedback - I added these links to the failover chapters. They will be visible with the next update on SAP Help Portal. 
Kind regards and happy holidays! Anna
