### ISSUE TITLE
Feedback for "Getting Started Checklist"

### ISSUE THREAD

**Issue by jannikvlk** [SAP-docs/btp-best-practices-guide#5]
https://help.sap.com/products/BTP/df50977d8bfa4c9a8a063ddb37113c43/cbd76632d8aa4cb7bbf175d7607db463.html?locale=en-US

This Link leads nowhere: Getting Started Checklist/ Step 2: Use Cases on SAP BTP https://help.sap.com/docs/link-disclaimer?site=https%3A%2F%2Fwww.sap.com%2Fproducts%2Fbusiness-technology-platform%2Fuse-cases.htmll
Because there is an additional 'L' at the end of the link that shouldn't be there. ('.htmll' should be '.html')

**Comment by annawenger20** [comment]
Thanks for spotting this, @jannikvlk! 
I just corrected it here and it should be visible soon on SAP Help Portal as well. 
Best regards,
Anna
