### ISSUE TITLE
Feedback for "Getting Started Checklist"

### ISSUE THREAD

**Issue by stefannothaft** [SAP-docs/btp-best-practices-guide#9]
https://help.sap.com/docs/BTP/df50977d8bfa4c9a8a063ddb37113c43/cbd76632d8aa4cb7bbf175d7607db463.html?locale=en-US

The learning journey seems to be outdated. Why not refer to https://learning.sap.com/learning-journey/discover-sap-business-technology-platform/get-an-overview-of-the-intelligent-sustainable-enterprise ?

**Comment by annawenger20** [comment]
Hi @stefannothaft, thanks a lot for this hint. I updated the chapter according to your proposal and will add some more information about the intelligent enterprise and SAP BTP's role in it.  
The update will be visible on SAP Help Portal with the next release, which should be on May 19th. 
Kind regards,
Anna
